Pergo/ViewModels/Comparison/ComparisonTableView.cs
using Pergo.ViewModels.Series;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Pergo.ViewModels.Comparison
{
    public class ComparisonTableView : FooterView
    {
        public SeriesView FirstSeries { get; set; }
        public SeriesView SecondSeries { get; set; }
        public LevelView FirstSeriesSpec { get; set; }
        public LevelView SecondSeriesSpec { get; set; }

        public int CH { get; set; }
    }
}

Pergo/ViewModels/Comparison/IndexView.cs
using Pergo.ViewModels.Series;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Pergo.ViewModels.Comparison
{
    public class IndexView : FooterView
    {
        public int CH { get; set; }
        public string CHStr { get; set; }
        public List<SeriesView> BrandSeriesList { get; set; }
    }
}

Pergo/Controllers/ComparisonController.cs
using AutoMapper;
using Pergo.Models;
using Pergo.Repositories;
using Pergo.ViewModels.Comparison;
using Pergo.ViewModels.Series;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pergo.Controllers
{
    public class ComparisonController : BaseController
    {
        private SeriesRepository seriesRepository;
        private LevelRepository levelRepository;
        private ProductRepository productRepository;

        public ComparisonController() : this(null, null, null) { }

        public ComparisonController(SeriesRepository repo, LevelRepository repo2, ProductRepository repo3)
        {
            seriesRepository = repo ?? new SeriesRepository(new PergoDBEntities());
            levelRepository = repo2 ?? new LevelRepository(new PergoDBEntities());
            productRepository = repo3 ?? new ProductRepository(new PergoDBEntities());
        }

        // GET: Comparison
        public ActionResult Index(int ch = 0, string value = "")
        {
            IndexView model = new IndexView();
            var seriesList = seriesRepository.Query(true, ch, "");
            if (ch != 0)
            {               
                model.CH = ch;
                model.CHStr = Pergo.Utility.Cmind.EnumHelper.GetDescription((Pergo.Models.BrandValue)ch);
            }
            model.BrandSeriesList = Mapper.Map<List<SeriesView>>(seriesList);
            model.SEOInfo = Mapper.Map<Pergo.Areas.Admin.ViewModels.SEO.SEOView>(GetSEO);

            return View(model);
        }

        public ActionResult ComparisonTable(int sa = 0, int sb = 0, int ch = 0, string value = "")
        {
            if (sa == 0 || sb == 0)
            {
                return RedirectToAction("Index", new { ch = ch });
            }
            ComparisonTableView model = new ComparisonTableView();
            model.CH = ch;
            try
            {            
                model.FirstSeries = Mapper.Map<SeriesView>(seriesRepository.GetById(sa));
                int la = model.FirstSeries.Brand == 1 ? 1 : 5; 
                var levelA = levelRepository.Query(true).Where(l => l.Level == la && l.SeriesID == sa).FirstOrDefault();
                model.FirstSeriesSpec = Mapper.Map<LevelView>(levelA);
                model.FirstSeriesSpec.ColorList = Mapper.Map<List<ColorView>>(productRepository.GetAll().Where(c => c.IsOnline == true && c.SeriesID == sa).ToList());

                model.SecondSeries = Mapper.Map<SeriesView>(seriesRepository.GetById(sb));
                int lb = model.SecondSeries.Brand == 1 ? 1 : 5; 
                var levelB = levelRepository.Query(true).Where(l => l.Level == lb && l.SeriesID == sb).FirstOrDefault();
                model.SecondSeriesSpec = Mapper.Map<LevelView>(levelB);
                model.SecondSeriesSpec.ColorList = Mapper.Map<List<ColorView>>(productRepository.GetAll().Where(c => c.IsOnline == true && c.SeriesID == sb).ToList());

                model.SEOInfo = Mapper.Map<Pergo.Areas.Admin.ViewModels.SEO.SEOView>(GetSEO);

                return View(model);
            }
            catch (Exception ex)
            {
                return View(model);
            }
            
        }
    }
}

Pergo/Views/Comparison/ComparisonTable.cshtml
@model Pergo.ViewModels.Comparison.ComparisonTableView

@{ 
    var FirstSeries = Model.FirstSeries;
    var SecondSeries = Model.SecondSeries;
    var FirstSeriesSpec = Model.FirstSeriesSpec;
    var SecondSeriesSpec = Model.SecondSeriesSpec;
    string Title = Model.CH == 0 ? "比較地板系列" : "比較" + Pergo.Utility.Cmind.EnumHelper.GetDescription((Pergo.Models.BrandValue)FirstSeries.Brand) + "系列";
}

    <section class="inset-shadow">
        <div class="container text-4d h5 text-lg-nowrap py-8">
            <h2 class="rwd-title text-center text-body mb-6">@Title</h2>
            @if (Model.CH == 0) {
            <div class="text-center"><a class="h5 text-center" href="@Url.Action("Index", "Comparison")">選項其它系列進行比較 ></a></div>
            }
            else
            {
            <div class="text-center"><a class="h5 text-center" href="@Url.Action("Index", "Comparison", new { ch = Model.CH, value = Pergo.Utility.Cmind.EnumHelper.GetDescription((Pergo.Models.BrandValue)FirstSeries.Brand) })">選項其它系列進行比較 ></a></div>
            }
            <div class="row justify-content-center">
          <div class="col-xl-10">
            <div class="row justify-content-around no-gutters mt-9 grid-table">
                <div class="col-5 col-lg-4 text-center">
                    <figure class="figure">
                        <img class="img-fluid" src="~/FileUploads/SeriesPhoto/@FirstSeries.CasePic" title="sensation 森系列" alt="sensation 森系列" />
                        <figcaption class="my-4">@FirstSeries.SeriesEngName @FirstSeries.SeriesName</figcaption><a class="h5" href="/Series/Overview/@FirstSeries.SeriesEngName.Replace(" ", "")">了解更多 ></a>
                    </figure>
                </div>
                <div class="col-5 col-lg-4 text-center">
                    <figure class="figure">
                        <img class="img-fluid" src="~/FileUploads/SeriesPhoto/@SecondSeries.CasePic" title="long plank 長版系列" alt="long plank 長版系列" />
                        <figcaption class="my-4">@SecondSeries.SeriesEngName @SecondSeries.SeriesName</figcaption><a class="h5" href="/Series/Overview/@SecondSeries.SeriesEngName.Replace(" ", "")">了解更多 ></a>
                    </figure>
                </div>

                <div class="col-12 border-bottom mt-lg-8">
                    <h3 class="h4">尺寸</h3>
                </div>
                <div class="col-6 col-lg-3">
                    <ul class="mt-lg-8">
                        @if (FirstSeriesSpec != null && !string.IsNullOrEmpty(FirstSeriesSpec.Length))
                         {
                        <li class="mb-2">長度：@FirstSeriesSpec.Length</li>
                         }
                        @if (FirstSeriesSpec != null && !string.IsNullOrEmpty(FirstSeriesSpec.Thickness))
                         {
                        <li class="mb-2">厚度：@FirstSeriesSpec.Thickness</li>
                         }
                    </ul>
                </div>
                <div class="col-6 col-lg-3">
                    <ul class="mt-lg-8">
                        @if (SecondSeriesSpec != null && !string.IsNullOrEmpty(SecondSeriesSpec.Length))
                         {
                        <li class="mb-2">長度：@SecondSeriesSpec.Length</li>
                         }
                        @if (SecondSeriesSpec != null && !string.IsNullOrEmpty(SecondSeriesSpec.Thickness))
                         {
                        <li class="mb-2">厚度：@SecondSeriesSpec.Thickness</li>
                         }
                    </ul>
                </div>

                <div class="col-12 border-bottom mt-lg-8">
                    <h3 class="h4">倒角</h3>
                </div>
                <div class="col-6 col-lg-3">
                    <ul class="mt-lg-8">
                         @if (FirstSeriesSpec != null && !string.IsNullOrEmpty(FirstSeriesSpec.Chamfer))
                         {
                        <li class="mb-2">@FirstSeriesSpec.Chamfer</li>
                         }
                    </ul>
                </div>
                <div class="col-6 col-lg-3">
                    <ul class="mt-lg-8">
                         @if (SecondSeriesSpec != null && !string.IsNullOrEmpty(SecondSeriesSpec.Chamfer))
                         {
                         <li class="mb-2">@SecondSeriesSpec.Chamfer</li>
                         }                       
                    </ul>
                </div>

                <div class="col-12 border-bottom mt-lg-8">
                    <h3 class="h4">工藝技術</h3>
                </div>
                <div class="col-6 col-lg-3">
                    <ul class="mt-lg-8">
                        @if(FirstSeriesSpec != null && !string.IsNullOrEmpty(FirstSeriesSpec.Tech))
                        { 
                            foreach (var item in FirstSeriesSpec.Tech.Split(','))
                            {
                            <li class="mb-2">@item</li>
                            }
                        }
                    </ul>
                </div>
                <div class="col-6 col-lg-3">
                    <ul class="mt-lg-8">
                        @if (SecondSeriesSpec != null && !string.IsNullOrEmpty(SecondSeriesSpec.Tech))
                        {
                            foreach (var item in SecondSeriesSpec.Tech.Split(','))
                            {
                        <li class="mb-2">@item</li>
                            }
                        }
                    </ul>
                </div>

                <div class="col-12 border-bottom mt-lg-8">
                    <h3 class="h4">表層壓紋</h3>
                </div>
                <div class="col-6 col-lg-3">
                    <ul class="mt-lg-8">
                        @if (FirstSeriesSpec != null && !string.IsNullOrEmpty(FirstSeriesSpec.Texture))
                        {
                            foreach (var item in FirstSeriesSpec.Texture.Split(','))
                            {
                        <li class="mb-2">@item</li>
                            }
                        }
                    </ul>
                </div>
                <div class="col-6 col-lg-3">
                    <ul class="mt-lg-8">
                        @if (SecondSeriesSpec != null && !string.IsNullOrEmpty(SecondSeriesSpec.Texture))
                        {
                            foreach (var item in SecondSeriesSpec.Texture.Split(','))
                            {
                        <li class="mb-2">@item</li>
                            }
                        }
                    </ul>
                </div>

                <div class="col-12 border-bottom mt-lg-8">
                    <h3 class="h4">亮澤</h3>
                </div>
                <div class="col-6 col-lg-3">
                    <ul class="mt-lg-8">
                        @if (FirstSeriesSpec != null && !string.IsNullOrEmpty(FirstSeriesSpec.Luster))
                        {
                            foreach (var item in FirstSeriesSpec.Luster.Split(','))
                            {
                        <li class="mb-2">@item</li>
                            }
                        }
                    </ul>
                </div>
                <div class="col-6 col-lg-3">
                    <ul class="mt-lg-8">
                        @if (SecondSeriesSpec != null && !string.IsNullOrEmpty(SecondSeriesSpec.Luster))
                        {
                            foreach (var item in SecondSeriesSpec.Luster.Split(','))
                            {
                        <li class="mb-2">@item</li>
                            }
                        }
                    </ul>
                </div>

                <div class="col-12 border-bottom">
                    <h3 class="h4">花色</h3>
                </div>
                <div class="col-5 col-lg-3 my-lg-8">
                    <div class="form-row">
                        @if (FirstSeriesSpec != null && FirstSeriesSpec.ColorList != null)
                        {
                            foreach (var item in FirstSeriesSpec.ColorList)
                            {
                                string name = $"{item.EngName} {item.Name}";
                        <div class="col-md-6 col-xl-4 col-xxl-3 my-1">
                            <div class="show-left bg-square" style="background-image:url(/FileUploads/ProductPhoto/@item.MainPic)" data-toggle="modal" data-target=".showDetail" data-name="@name" data-img="/FileUploads/ProductPhoto/@item.MainPic" data-href="@Url.Action("Color", "Series", new { sid = item.SeriesID, cid = $"1-{item.ID}", value = Pergo.Utility.Cmind.EnumHelper.GetDescription((Pergo.Models.BrandValue)FirstSeries.Brand) })"></div>
                        </div>
                            }
                        }
                    </div>
                </div>
                <div class="col-5 col-lg-3 my-lg-8">
                    <div class="form-row">
                        @if (SecondSeriesSpec != null && SecondSeriesSpec.ColorList != null)
                        {
                            foreach (var item in SecondSeriesSpec.ColorList)
                            {
                                string name = $"{item.EngName} {item.Name}";
                        <div class="col-md-6 col-xl-4 col-xxl-3 my-1">
                            <div class="show-left bg-square" style="background-image:url(/FileUploads/ProductPhoto/@item.MainPic)" data-toggle="modal" data-target=".showDetail" data-name="@name" data-img="/FileUploads/ProductPhoto/@item.MainPic" data-href="@Url.Action("Color", "Series", new { sid = item.SeriesID, cid = $"1-{item.ID}", value = Pergo.Utility.Cmind.EnumHelper.GetDescription((Pergo.Models.BrandValue)SecondSeries.Brand) })"></div>
                        </div>
                            }
                        }
                    </div>
                </div>

            </div>
        </div>
        </div>
        </div>
    </section>
    <div class="modal fade showDetail" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
        <div class="modal-dialog mt-md-8">
            <div class="modal-content bg-transparent border-0">
                <a class="text-hide text-right" href="#" data-dismiss="modal" aria-label="Close">close<img src="~/Content/img/icon-cross.svg" alt="close" width="40" height="40" /></a>
                <div class="carousel slide" id="carousel" data-ride="carousel">
                    <div class="carousel-inner"></div>
                </div>
                <a class="carousel-control-prev" id="carousel-prev" href="#carousel" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon-white" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" id="carousel-next" href="#carousel" role="button" data-slide="next">
                    <span class="carousel-control-next-icon-white" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
                @*<a class="carousel-prev" id="carousel-prev" href="#carousel" role="button" data-slide="prev" style="top:40%; bottom:40%;">
                    <span class="prev-arrow-line" aria-hidden="true"></span>
                </a>
                <a class="carousel-next" id="carousel-next" href="#carousel" role="button" data-slide="next" style="top:40%; bottom:40%;">
                    <span class="next-arrow-line" aria-hidden="true"></span>
                </a>*@
            </div>
        </div>
    </div>

@section bread{
    <li class="breadcrumb-item active" aria-current="page">產品比較</li>
}

@section scripts{
    <script>
        $(function () {
            $('.menu_4').addClass('active');
            setTimeout(function () {
                $('.checkbox-round').each(function () {
                    $(this).prop('checked,false')
                });
            }, 0);          
        });
    </script>
}

Pergo/Views/Comparison/Index.cshtml
@model Pergo.ViewModels.Comparison.IndexView
@{ 
    string Title = string.IsNullOrEmpty(Model.CHStr) ? "比較地板系列" : "比較" + Model.CHStr + "系列";
    string brandStr = Model.CH == 2 ? "Vinyl" : "Laminate";
}

<section class="inset-shadow">
    <div class="container text-center py-8">
        <h2 class="rwd-title mb-5">@Title</h2>
        <p class="rwd-subtitle font-weight-normal mb-7">從以下選項中挑選出兩種您心儀的地板系列進行比較。</p>
        <a class="btn btn-twin py-2 px-6 rounded-lg mb-8" id="showTable" href="#">比較系列</a>
        <div class="row justify-content-center">
            <div class="col-xxl-10">
                <div class="comparison-plank">
                    @for (int i = 0; i < Model.BrandSeriesList.Count(); i++)
                    {
                        string compare = "compare" + i;
                        var data = Model.BrandSeriesList[i];
                        <div class="text-center px-2">
                            <input class="checkbox-round" type="checkbox" id="@compare" value="@data.ID" name="compareSample" />
                            <label class="d-block mt-2 hover-mask" for="@compare">
                                <figure class="figure">
                                    <div class="checked-border mb-4">
                                        <img class="img-fluid" src="~/FileUploads/SeriesPhoto/@data.SamplePic" title="@data.SeriesName" alt="@data.SeriesName" />
                                        <div class="hover-group">
                                            <h3 class="rwd-subtitle font-weight-normal">@data.SeriesName</h3><a class="add-fav" href="#"><span class="icon icon-heart"></span></a>
                                        </div>
                                    </div>
                                    <figcaption class="text-center">@data.SeriesName</figcaption>
                                </figure>
                            </label>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>

@section scripts{
    <script src="~/Content/js/slick.js"></script>
    <script>
        var compareItems = [];
        $(function () {
            $('.menu_4').addClass('active');
            $('input[name="compareSample"]').each(function () {
                compareItems = [];
                $(this).prop('checked', false);
            });
        });

        $('.comparison-plank').slick({
            infinite: true,
            slidesToShow: $(window).width() < 768 ? 3 : 5,
            slidesToScroll: $(window).width() < 768 ? 3 : 5,
            prevArrow: '<a class="carousel-control-prev" href="#" role="button" style="left:-5%; top:40%;bottom:40%"><span class="carousel-control-prev-icon" aria-hidden="true"></span><span class="sr-only">Previous</span></a>',
            nextArrow: '<a class="carousel-control-next" href="#" role="button" style="right:-5%; top:40%;bottom:40%"><span class="carousel-control-next-icon" aria-hidden="true"></span><span class="sr-only">Next</span></a>'
        })      
        $('#showTable').on('click', function (e) {
            if (compareItems.length < 2) {
                alert('請選擇比較系列 ! ');
                e.preventDefault();
            }
            else {
                window.location.href = `@Url.Action("ComparisonTable", "Comparison")?sa=${compareItems[0]}&sb=${compareItems[1]}&ch=@(Model.CH)&value=@(brandStr)`;
            }
        });
        $('input[name="compareSample"]').on('change', function () {
            let exist = compareItems.indexOf($(this).val()) === -1 ? false : true;
            let arrayIndex = compareItems.indexOf($(this).val());
            //確認比較項目以點選 ? 刪除 : (新增條件只能兩項 ? 刪除陣列[0] → 新增 : 直接新增)
            if (exist) {
                compareItems.splice(arrayIndex, 1)
            } else {
                if (compareItems.length === 2) {
                    $(`input[value=${compareItems[0]}]`).prop('checked', false);
                    compareItems.splice(0, 1);
                }
                compareItems.push($(this).val());
            }
        });

    </script>
}

@section bread{
    <li class="breadcrumb-item active" aria-current="page">產品比較</li>
}