Pergo/Areas/Admin/ViewModels/Documentation/DocumentationIndexView.cs
using Pergo.Models;
using Pergo.Models.Cmind;
using Pergo.Utility.Cmind;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pergo.Areas.Admin.ViewModels.Documentation
{
    public class DocumentationIndexView : PageQuery
    {
        public DocumentationIndexView()
        {
            this.Sorting = "Title";
            this.IsDescending = false;
        }

        public PageResult<DocumentationView> PageResult { get; set; }

        [Display(Name = "是否上線")]
        public bool? IsOnline { get; set; }

        [Display(Name = "標題名稱")]
        public string Title { get; set; }

        //[Display(Name = "類別")]
        //public int Type { get; set; }

        //public List<SelectListItem> DocumentationTypeOptions
        //{
        //    get
        //    {
        //        List<SelectListItem> result = new List<SelectListItem>();
        //        var values = EnumHelper.GetValues<DocumentationType>();
        //        foreach (var v in values)
        //        {
        //            result.Add(new SelectListItem()
        //            {
        //                Text = EnumHelper.GetDescription(v),
        //                Value = ((int)v).ToString()
        //            });
        //        }
        //        return result;
        //    }
        //}
    }
}

Pergo/Areas/Admin/ViewModels/Documentation/DocumentationView.cs
using Pergo.Models;
using Pergo.Utility.Cmind;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pergo.Areas.Admin.ViewModels.Documentation
{
    public class DocumentationView
    {
        [Display(Name = "ID")]
        public int ID { get; set; }

        [Required]
        [Display(Name = "標題名稱")]
        public string Title { get; set; }

        [Display(Name = "檔案名稱")]
        public string FileName { get; set; }

        [Display(Name = "圖片")]
        public string MainPic { get; set; }

        [Display(Name = "文件類型")]
        public string Type { get; set; }

        [Display(Name = "排序")]
        public int Sort { get; set; }

        [Display(Name = "是否上線")]
        public bool IsOnline { get; set; }

        [Display(Name = "更新時間")]
        public DateTime UpdateDate { get; set; }

        [Display(Name = "更新者")]
        public int Updater { get; set; }

        [Display(Name = "建立時間")]
        public DateTime CreateDate { get; set; }

        [Display(Name = "建立者")]
        public int Creater { get; set; }

        //public List<SelectListItem> DocumentationTypeOptions
        //{
        //    get
        //    {
        //        List<SelectListItem> result = new List<SelectListItem>();
        //        var values = EnumHelper.GetValues<DocumentationType>();
        //        foreach (var v in values)
        //        {
        //            result.Add(new SelectListItem()
        //            {
        //                Text = EnumHelper.GetDescription(v),
        //                Value = ((int)v).ToString()
        //            });
        //        }
        //        return result;
        //    }
        //}
    }
}

Pergo/Areas/Admin/ViewModels/FAQ/FAQIndexView.cs
using Pergo.Models;
using Pergo.Models.Cmind;
using Pergo.Repositories;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pergo.Areas.Admin.ViewModels.FAQ
{
    public class FAQIndexView : PageQuery
    {
        public FAQIndexView()
        {
            this.Sorting = "Sort";
            this.IsDescending = false;
        }

        public PageResult<FAQView> PageResult { get; set; }

        [Display(Name = "問題")]
        public string Question { get; set; }

        [Display(Name = "地板類型")]
        public int BrandType { get; set; }

        [Display(Name = "問題類型")]
        public int QuestionType { get; set; }

        [Display(Name = "排序")]
        public int Sort { get; set; }

        [Display(Name = "上線狀態")]
        public bool? IsOnline { get; set; }

        public List<SelectListItem> BrandTypeOptions
        {
            get
            {
                List<SelectListItem> result = new List<SelectListItem>();
                result.Add(new SelectListItem()
                {
                    Text = "全部",
                    Value = "0"
                });
                result.Add(new SelectListItem()
                {
                    Text = "超耐磨木地板",
                    Value = "1"
                });
                result.Add(new SelectListItem()
                {
                    Text = "防水地板",
                    Value = "2"
                });

                return result;
            }
        }

        FAQTypeRepository faqTypeRepository = new FAQTypeRepository(new PergoDBEntities());
        public List<SelectListItem> QuestionTypeOptions
        {
            get
            {
                List<SelectListItem> result = new List<SelectListItem>();
                var values = faqTypeRepository.GetAll().Where(s => s.IsOnline == true).ToList();
                foreach (var v in values)
                {
                    result.Add(new SelectListItem()
                    {
                        Text = v.Name,
                        Value = v.ID.ToString()
                    });
                }
                return result;
            }
        }

        //public List<SelectListItem> QuestionTypeOptions
        //{
        //    get
        //    {
        //        List<SelectListItem> result = new List<SelectListItem>();
        //        result.Add(new SelectListItem()
        //        {
        //            Text = "保養相關",
        //            Value = "1"
        //        });
        //        result.Add(new SelectListItem()
        //        {
        //            Text = "收編相關",
        //            Value = "2"
        //        });

        //        return result;
        //    }
        //}
    }
}

Pergo/Areas/Admin/ViewModels/Store/StoreIndexView.cs
using Pergo.Models.Cmind;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Pergo.Areas.Admin.ViewModels.Store
{
    public class StoreIndexView : PageQuery
    {
        public StoreIndexView()
        {
            this.Sorting = "StoreName";
            this.IsDescending = false;
        }

        public PageResult<StoreView> PageResult { get; set; }

        [Display(Name = "門市名稱")]
        public string StoreName { get; set; }

        [Display(Name = "門市地址")]
        public string Address { get; set; }

        [Display(Name = "門市照片")]
        public string StorePic { get; set; }

        [Display(Name = "上線狀態")]
        public bool? IsOnline { get; set; }
    }
}

Pergo/Models/Documentation.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pergo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documentation
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string FileName { get; set; }
        public string MainPic { get; set; }
        public string Type { get; set; }
        public int Sort { get; set; }
        public bool IsOnline { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int Updater { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int Creater { get; set; }
    }
}

Pergo/Controllers/SupportController.cs
using AutoMapper;
using Pergo.Models;
using Pergo.Repositories;
using Pergo.Utility.Cmind;
using Pergo.ViewModels.Support;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pergo.Controllers
{
    public class SupportController : BaseController
    {
        private FAQRepository faqRepository;
        private CaseRepository caseRepository;
        private DocumentationRepository documentationRepository;
        private ReservationRepository reservationRepository;
        private StoreRepository storeRepository;
        private DocumentationMailLogRepository documentationMailLogRepository;

        public SupportController() : this(null, null, null, null, null, null) { }

        public SupportController(FAQRepository repo, CaseRepository repo2, DocumentationRepository repo3, ReservationRepository repo4, StoreRepository repo5, DocumentationMailLogRepository repo6)
        {
            faqRepository = repo ?? new FAQRepository(new PergoDBEntities());
            caseRepository = repo2 ?? new CaseRepository(new PergoDBEntities());
            documentationRepository = repo3 ?? new DocumentationRepository(new PergoDBEntities());
            reservationRepository = repo4 ?? new ReservationRepository(new PergoDBEntities());
            storeRepository = repo5 ?? new StoreRepository(new PergoDBEntities());
            documentationMailLogRepository = repo6 ?? new DocumentationMailLogRepository(new PergoDBEntities());
        }

        // GET: Service
        public ActionResult Index()
        {
            SupportView model = new SupportView();
            model.SEOInfo = Mapper.Map<Pergo.Areas.Admin.ViewModels.SEO.SEOView>(GetSEO);

            return View(model);
        }

        /// <summary>
        /// 線上預約
        /// </summary>
        /// <returns></returns>
        public ActionResult Reservation()
        {
            return View();
        }

        /// <summary>
        /// 產品保固
        /// </summary>
        /// <returns></returns>
        public ActionResult Warranty()
        {
            return View();
        }

        /// <summary>
        /// FAQs
        /// </summary>
        /// <returns></returns>
        public ActionResult FAQ()
        {
            FAQView model = new FAQView();
            model.FAQList = Mapper.Map<List<FAQDataView>>(faqRepository.GetAll().Where(f => f.IsOnline == true).OrderBy(f => f.Sort).ToList());
            model.SEOInfo = Mapper.Map<Pergo.Areas.Admin.ViewModels.SEO.SEOView>(GetSEO);

            return View(model);
        }

        /// <summary>
        /// 施工流程
        /// </summary>
        /// <returns></returns>
        public ActionResult Construction()
        {
            return View();
        }

        /// <summary>
        /// 文件下載
        /// </summary>
        /// <returns></returns>
        public ActionResult Documentation()
        {
            DocumentationView model = new DocumentationView();
            model.DocumentationList = Mapper.Map<List<Pergo.Areas.Admin.ViewModels.Documentation.DocumentationView>>(documentationRepository.Query(true).OrderBy(d => d.Sort).ToList());
            model.SEOInfo = Mapper.Map<Pergo.Areas.Admin.ViewModels.SEO.SEOView>(GetSEO);

            return View(model);
        }

        /// <summary>
        /// 維護與清潔
        /// </summary>
        /// <returns></returns>
        public ActionResult Maintenance()
        {
            MaintenanceView model = new MaintenanceView();

            return View(model);
        }

        /// <summary>
        /// 案例分享
        /// </summary>
        /// <returns></returns>
        public ActionResult Case()
        {
            return View();
        }

        /// <summary>
        /// 搜尋門市
        /// </summary>
        /// <returns></returns>
        public ActionResult Store()
        {
            StoreView model = new StoreView();
            model.StoreList = Mapper.Map<List<StoreDataView>>(storeRepository.GetAll().Where(s => s.IsOnline == true).OrderBy(s => s.Sort).ToList());
            model.SEOInfo = Mapper.Map<Pergo.Areas.Admin.ViewModels.SEO.SEOView>(GetSEO);

            return View(model);
        }

        /// <summary>
        /// 支援服務共用
        /// </summary>
        /// <returns></returns>
        public ActionResult Service()
        {
            return PartialView();
        }

        [HttpPost]
        public JsonResult GetFAQ()
        {
            var result = Mapper.Map<List<FAQDataView>>(faqRepository.GetAll().Where(f => f.IsOnline == true).OrderBy(f => f.Sort).ToList());

            return Json(result);
        }

        /// <summary>
        /// 聯絡表單
        /// </summary>
        /// <param name="type"></param>
        /// <returns></returns>
        public ActionResult ContactUs(int type = 0)
        {
            ContactUsView model = new ContactUsView();
            model.Type = type;
            //model.ReservationTime = DateTime.Now.AddDays(1);
            //model.ReservationTimeStr = model.ReservationTime.ToString("yyyy/MM/dd HH:mm");
            model.SEOInfo = Mapper.Map<Pergo.Areas.Admin.ViewModels.SEO.SEOView>(GetSEO);
            return View(model);
        }

        [HttpPost]
        public ActionResult ContactUs(ContactUsView model)
        {
            model.ReservationTime = Convert.ToDateTime(model.ReservationTimeStr);
            if (ModelState.IsValid)
            {
                Reservation reservation = Mapper.Map<Reservation>(model);
                reservation.CreateDate = DateTime.Now;
                model.ID = reservationRepository.Insert(reservation);

                //寄信通知管理員
                SendRemindMail(reservation, "marketing@pergo.com.tw", true);
                SendRemindMail(reservation, reservation.Email);

                ShowMessage(true, "資料已送出。");
                return Redirect("/Support/ContactResult?cid=" + model.ID + "#contact_result");
            }
            else
            {
                ShowMessage(false, "資料格式錯誤。");
                model.SEOInfo = Mapper.Map<Pergo.Areas.Admin.ViewModels.SEO.SEOView>(GetSEO);
                return View(model);
            }
        }

        /// <summary>
        /// 表單結果
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult ContactResult(int cid = 0)
        {
            ContactUsView model = new ContactUsView();
            var query = reservationRepository.GetById(cid);
            model = Mapper.Map<ContactUsView>(query);
            model.ReservationTimeStr = model.ReservationTime.ToString("yyyy/MM/dd HH:mm");
            if (!string.IsNullOrEmpty(model.Store)) {
                model.StoreInfo = Mapper.Map<StoreDataView>(storeRepository.GetById(Convert.ToInt32(model.Store)));
            }
            model.SEOInfo = Mapper.Map<Pergo.Areas.Admin.ViewModels.SEO.SEOView>(GetSEO);

            return View(model);
        }

        /// <summary>
        /// 寄信通知管理員
        /// </summary>
        /// <param name="email"></param>
        /// <param name="doclist"></param>
        /// <returns></returns>
        public string SendRemindMail(Reservation reservation, string email = "", bool isAdmin = false)
        {
            try
            {
                //email = "a842695137@gmail.com";
                string Title = $"Pergo 百力地板預約";
                string mailbody = "";
                string AdminLink = $"{Request.Url.Authority}/Admin/ReservationAdmin/Edit/{reservation.ID}";

                #region MailBody
                mailbody += @"<div>
                                        <div>" +
                                            "<h3>預約資訊 : </h3>" +
                                            $"<p><span style='font-weight: bold;'>姓名 :</span> { reservation.Name }</p>" +
                                            $"<p><span style='font-weight: bold;'>分類 : </span>{ Pergo.Utility.Cmind.EnumHelper.GetDescription((Pergo.Models.ReservationType)reservation.Type) }</p>" +
                                            $"<p><span style='font-weight: bold;'>電話 : </span>{ reservation.Phone }</p>" +
                                            $"<p><span style='font-weight: bold;'>地址 : </span>{ reservation.Address }</p>" +
                                            $"<p><span style='font-weight: bold;'>門市 : </span>{ storeRepository.GetById(Convert.ToInt32(reservation.Store)).StoreName }</p>" +
                                            $"<p><span style='font-weight: bold;'>信箱 : </span>{ reservation.Email }</p>" +
                                            $"<p><span style='font-weight: bold;'>詢問內容 : </span>{ reservation.InquiryContent }</p><br/>" +
                                            $"<p><span style='font-weight: bold;'>預約時間 : </span>{ reservation.ReservationTime.ToString("yyyy/MM/dd HH:mm") }</p>";
                                        if (isAdmin)
                                        {
                                    mailbody += "<br/>" +
                                    $"<p><a href='{AdminLink}'>後台連結</a></p>";
                                        }

                                    mailbody += @"
                                            <br/>
                                            <br/>                                            
                                            <p>Pergo 敬上</p>
                                            </div>   
                                        </div>";
                #endregion

                SendMail(email, mailbody, Title, "", "");

                return "Success";
            }
            catch (Exception ex)
            {
                return "Failed";
            }
        }

        /// <summary>
        /// 寄送文件
        /// </summary>
        /// <param name="email"></param>
        /// <param name="datalist"></param>
        /// <returns></returns>

Pergo/Views/Support/ContactResult.cshtml
@model Pergo.ViewModels.Support.ContactUsView

@section header{
}

@Html.Partial("Service")

<section id="contact_result">
    <div class="container-fluid"></div>
    <div class="container-fluid border-top">
        <div class="row justify-content-center my-4">
            <div class="col-xl-6" style="margin-left:5%;margin-top:5%;">
                <div style="text-align:center; font-weight:bold;">
                    <p style="font-size: 44px;">您已經完成預約申請</p>
                    <p style="font-size: 24px;">我們將傳送信件至您的電子郵件，請依e-mail資訊為主。</p>
                    <div style="padding-top:100px; padding-bottom:80px;">

                        <a href="@Url.Action("Index", "Support")"><span style="font-size: 34px; color: #e6b300;">查看更多服務 > </span></a>
                    </div>
                </div>

                <div style="border-width: 1px; padding: 30px; border-style: outset; box-shadow: 2px 2px 4px 2px #cccccc;">
                    @if (!string.IsNullOrEmpty(Model.Store)) {                        
                        <img src="~/FileUploads/StorePhoto/@Model.StoreInfo.StorePic" style="width: 250px;"/>            
                    }
                    <table style="display:inline; vertical-align: middle; display: inline-block; font-weight:bold; font-size: 20px;">
                        @{ 
                            var culture = new System.Globalization.CultureInfo("zh-HK");
                            var day = culture.DateTimeFormat.GetDayName(Model.ReservationTime.DayOfWeek);                           
                            var time = culture.DateTimeFormat.GetDayName(Model.ReservationTime.DayOfWeek);                           
                        }
                        <tr>
                            <td><label>@Model.ReservationTime.ToString("yyyy年MM月dd日")，@day</label></td>
                        </tr>
                        <tr>
                            <td>時間 : @Model.ReservationTime.ToString("ttHH:mm(GMT +8)")</td>
                        </tr> 
                        <tr>
                            <td>@Html.LabelFor(model => model.Name) : @Model.Name</td>                      
                        </tr> 
                        <tr>
                            <td>@Html.LabelFor(model => model.Phone) : @Model.Phone</td>
                        </tr>
                        <tr>
                            <td>@Html.LabelFor(model => model.Email) : @Model.Email</td>
                        </tr>
                        <tr>
                            <td>@Html.LabelFor(model => model.Address) : @Model.Address</td>
                        </tr>
                        @if (!string.IsNullOrEmpty(Model.Store)) {         
                        <tr>                          
                            <td>地點 : @Model.StoreInfo.StoreName</td>
                        </tr>
                        }                      
                    </table>
                    <p style="padding-top: 20px; font-weight:bold; font-size: 20px;">@Html.LabelFor(model => model.InquiryContent) : <br />@Model.InquiryContent</p>
                </div>

            </div>
        </div>
    </div>
</section>

@section bread{
    <li class="breadcrumb-item"><a href="@Url.Action("Index", "Support" )">支援服務</a></li>
    <li class="breadcrumb-item"><a href="@Url.Action("ContactUs", "Support")">支援服務</a></li>
    <li class="breadcrumb-item active" aria-current="page">聯絡我們</li>
}

@section scripts{
    <!--顯示訊息-->
    <script src="~/Scripts/Admin/toastr/toastr.min.js"></script>
    <script src="~/Scripts/Admin/custom.js"></script>
    <!--datetimepicker-->
    <link href="~/Content/bootstrap-datetimepicker-master/css/bootstrap-datetimepicker.min.css" rel="stylesheet" />
    <script src="~/Content/bootstrap-datetimepicker-master/js/bootstrap-datetimepicker.js"></script>
    <script>
        $(function () {
            $('.menu_1').addClass('active');

            $('html, body').animate({
                scrollTop: $('#contact_result').offset().top
            }, 500);

            //datetimepicker
            $.prototype.datetimepicker.DPGlobal.nonpunctuation = /[^ -\/:-@@\[-`{-~\t\n\rZ]+/g;
            var currentDate = new Date();
            currentDate.setMinutes(0, 0, 0);
            currentDate.setHours(currentDate.getHours() + currentDate.getTimezoneOffset() / 60);
            $('#ReservationTimeStr').datetimepicker({
                todayHighlight: true,
                weekStart: 1,
                minView: 0,
                autoclose: true,
                //pickerPosition: 'bottom-left',
                format: 'yyyy/mm/dd hh:ii ',
                //timezone: 'UTC',
                startDate: currentDate,
            });
        });
    </script>
}

Pergo/Views/Support/ContactUs.cshtml
@model Pergo.ViewModels.Support.ContactUsView

@section header{
}

@Html.Partial("Service")

<section id="contactUs">
    <div class="container-fluid"></div>
    <div class="container-fluid border-top">
        <div class="row justify-content-center my-4">
            <div class="col-xl-6">
                <h3>請填寫您的預約資訊</h3>
                <p>將為您申請預約丈量的時間。</p>
                @using (Html.BeginForm("ContactUs", "Support", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="form-row">
                        <div class="col-lg-4 form-group">
                            @Html.LabelFor(model => model.Name)
                            @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @type = "text" })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-lg-8 form-group">
                            @Html.LabelFor(model => model.Phone)
                            @Html.TextBoxFor(model => model.Phone, new { @class = "form-control", @type = "tel" })
                            @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-12 form-group">
                            @Html.LabelFor(model => model.Address)
                            @Html.TextBoxFor(model => model.Address, new { @class = "form-control", @type = "text" })
                            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-12 form-group">
                            @Html.LabelFor(model => model.Email)
                            @Html.TextBoxFor(model => model.Email, new { @class = "form-control", @type = "email" })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-12 form-group">
                            @Html.LabelFor(model => model.Store)
                            @Html.DropDownListFor(model => model.Store, Model.StoreOptions, "", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Store, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-12 form-group">
                            @Html.LabelFor(model => model.ReservationTimeStr) &nbsp;(若無選擇將自動設為隔天同一時間)
                            @Html.TextBoxFor(model => model.ReservationTimeStr, new { @class = "form-control", @autocomplete = "off" })
                            @Html.ValidationMessageFor(model => model.ReservationTimeStr, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-12 form-group">
                            <label for="message">想要詢問的事項，將請專員為您解說</label>
                            @Html.TextAreaFor(model => model.InquiryContent, new { @class = "form-control", @type = "email", @rows = "10" })
                        </div>
                        <div class="col-2 form-group">
                            <button class="btn btn-outline-primary" id="send" type="submit">送出</button>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</section>

@section bread{
    <li class="breadcrumb-item"><a href="@Url.Action("Index", "Support" )">支援服務</a></li>
    <li class="breadcrumb-item active" aria-current="page">聯絡我們</li>
}

@section scripts{
    <!--顯示訊息-->
    <script src="~/Scripts/Admin/toastr/toastr.min.js"></script>
    <script src="~/Scripts/Admin/custom.js"></script>
    <script>
        $(function () {
            $('.menu_1').addClass('active');

            $('html, body').animate({
                scrollTop: $('#contactUs').offset().top
            }, 500);         
        });
    </script>

    <!--datetimepicker-->
 
    <link href="~/Content/bootstrap-datetimepicker-master/css/bootstrap-datetimepicker.min.css" rel="stylesheet" />
    <script src="~/Content/bootstrap-datetimepicker-master/js/bootstrap-datetimepicker.js"></script>
    <script type="text/javascript">
        $(function () {         
            //$('#ReservationTimeStr').keyup(function () {
            //    var nowTime = new Date();
            //    if (parseInt((nowTime - $(this).val())) / 1000 / 60 / 60 < 1) {
            //        alert('預約時間不可少於1小時 !!');
            //        if (nowTime.getHours() <= 17) {
            //            $(this).val(nowTime.setHours(nowTime.getHours()+1));
            //        }
            //        else {
            //            var tomorrow = nowTime.setHours(9, 00);                        
            //            $(this).val(tomorrow);
            //        }
            //    }
            //});

            //datetimepicker
            $.prototype.datetimepicker.DPGlobal.nonpunctuation = /[^ -\/:-@@\[-`{-~\t\n\rZ]+/g;
            var currentDate = new Date();
            //currentDate.setMinutes(0, 0, 0);
            currentDate.setHours(currentDate.getHours() + 1);
            if (currentDate.getHours() >= 17) {
                currentDate.setDate(currentDate.getDate() + 1)
                currentDate.setHours(09, 00);
            }                  
            //currentDate.setHours(currentDate.getHours() + currentDate.getTimezoneOffset() / 60);
            $('#ReservationTimeStr').datetimepicker({
                todayHighlight: true,
                //weekStart: 1,
                //weekEnd: 5,
                daysOfWeekDisabled: [0, 6],
                minView: 0,
                autoclose: true,
                //pickerPosition: 'bottom-left',
                format: 'yyyy/mm/dd hh:ii ',
                //timezone: 'UTC',
                startDate: currentDate,
                minHours: 10,
                maxHours: 17,
            });

            setTimeout(function () {
                var currentDateSec = new Date();
                currentDateSec.setHours(currentDateSec.getHours() + 1);
                if (currentDateSec.getHours() >= 17) {
                    currentDateSec.setDate(currentDateSec.getDate() + 1)
                    currentDateSec.setHours(09, 00);
                }            
                
                //currentDateSec.setHours(currentDateSec.getHours() + currentDateSec.getTimezoneOffset() / 60);
                $('#ReservationTimeStr').datetimepicker({
                    todayHighlight: true,
                    //weekStart: 1,
                    minView: 0,
                    autoclose: true,
                    //pickerPosition: 'bottom-left',
                    format: 'yyyy/mm/dd hh:ii ',
                    //timezone: 'UTC',
                    startDate: currentDateSec,
                    minHours: 9,
                    maxHours: 17,
                });
            }, 1800000);
            $('.datetimepicker-days').on('click', function () {            
                $('.hour').each(function () {
                    var value = $(this).text();
                    var f = +value.split(':')[0];
                    //console.log(f);
                    if (f < 9 || f > 17) {
                        $(this).addClass('disabled');
                        console.log(f);
                    }
                });
            });
        });
    </script>
}

Pergo/Views/Support/Index.cshtml
@model Pergo.ViewModels.Support.SupportView
@section header{
}

@Html.Partial("Service")

@section bread{
    <li class="breadcrumb-item"><a href="@Url.Action("Index", "Support" )">支援服務</a></li>
}

@section scripts{
    <script>
        $(function () {
            $('.menu_7').addClass('active');
        });
    </script>
}