Pergo/Areas/Admin/Controllers/MemberAdminController.cs
using Pergo.ActionFilters;
using Pergo.Areas.Admin.ViewModels.Member;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pergo.Areas.Admin.Controllers
{
    [Authorize]
    [ErrorHandleAdminActionFilter]
    public class MemberAdminController : BaseAdminController
    {
        // GET: Admin/MemberAdmin
        public ActionResult Subscribe(SubscribeIndexView model)
        {
            List<string> mailList = new List<string>();

            // 建立檔案串流（@ 可取消跳脫字元 escape sequence）
            StreamReader sr = new StreamReader(Server.MapPath(@"\App_Data\subscribeemail.txt"));
            while (!sr.EndOfStream)
            {               // 每次讀取一行，直到檔尾
                string line = sr.ReadLine();            // 讀取文字到 line 變數
                mailList.Add(line);
            }
            sr.Close();						// 關閉串流

            if (!string.IsNullOrEmpty(model.SearchValue))
            {
                mailList = mailList.Where(m => m.Contains(model.SearchValue)).ToList();
            }
            model.EmailList = mailList;

            return View(model);
        }

        /// <summary>
        /// 刪除管理者
        /// </summary>
        /// <param name="email"></param>
        /// <returns></returns>
        public string DelManager(string email)
        {        
            List<string> newList = new List<string>();

            StreamReader sr = new StreamReader(Server.MapPath(@"\App_Data\subscribeemail.txt"));
            while (!sr.EndOfStream)
            {               // 每次讀取一行，直到檔尾
                string line = sr.ReadLine();            // 讀取文字到 line 變數

                if (line != email)
                {
                    newList.Add(line);
                }
            }
            sr.Close();                     // 關閉串流

            try
            {
                using (StreamWriter outputFile = new StreamWriter(Path.Combine(Server.MapPath(@"\App_Data\"), "subscribeemail.txt"), false))
                {
                    foreach (var item in newList)
                    {
                        outputFile.WriteLine(item);
                    }
                    outputFile.Close();
                    return $" {email} 已取消訂閱 !";
                }
            }
            catch (Exception ex)
            {
                return $"操作失敗，請再試一次。 Message : {ex.Message}";
            }
        }
    }
}

Pergo/Areas/Admin/Views/MemberAdmin/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

Pergo/Areas/Admin/Views/MemberAdmin/Subscribe.cshtml
@model Pergo.Areas.Admin.ViewModels.Member.SubscribeIndexView
@{
}

<section class="content-header">
    <h1>
        訂閱管理
    </h1>
</section>

<section class="content">
    <div class="row">
        <!--搜尋條件-->
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">搜尋</h3>
                </div>
                @using (Html.BeginForm("Subscribe", "MemberAdmin", FormMethod.Get, new { @class = "form-horizontal" }))
                {
                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.SearchValue, new { @class = "col-sm-2 control-label" })
                            <div class="col-sm-10">
                                @Html.TextBoxFor(model => model.SearchValue, new { @class = "form-control", @id = "SeriesName", @placeholder = "系列名稱" })
                            </div>
                        </div>
                                             
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-info">搜尋</button>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>

        <!--清單-->
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">訂閱列表</h3>
                </div>
                <div class="box-body">
                    <div id="dataList_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                        <div class="row">
                            <div class="col-sm-12">
                                <table class="table table-bordered table-hover dataTable">
                                    <thead>
                                        <tr>                                           
                                            <th>
                                                訂閱Email
                                            </th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>
                                                訂閱Email
                                            </th>
                                            <th></th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        @foreach (var item in Model.EmailList)
                                        {
                                        <tr>
                                            <td>
                                                @item
                                            </td>
                                            <td>
                                                <button type="button" onclick="delmail('@item')" class="btn btn-danger">刪除/取消訂閱</button>
                                            </td>
                                        </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section scripts{
    <script>
        function delmail(email) {           
            if (!confirm(`確定要取消 ${email} 訂閱嗎 ? `)) {
                return false;
            }
            $.ajax({
                url: '@Url.Action("DelManager", "MemberAdmin")',
                type: "POST",
                data: { email: email },
                dataType: 'text',
                success: function (data) {
                    alert(data);
                    location.reload();
                }               
            });
        }
    </script>    
}