Pergo/Areas/Admin/Controllers/ReservationAdminController.cs
using AutoMapper;
using Pergo.ActionFilters;
using Pergo.Areas.Admin.ViewModels.Reservation;
using Pergo.Models;
using Pergo.Models.Cmind;
using Pergo.Repositories;
using Pergo.Utility.Cmind;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pergo.Areas.Admin.Controllers
{
    [Authorize]
    [ErrorHandleAdminActionFilter]
    public class ReservationAdminController : BaseAdminController
    {
        private ReservationRepository reservationRepository;
        private StoreRepository storeRepository;

        public ReservationAdminController() : this(null, null) { }

        public ReservationAdminController(ReservationRepository repo, StoreRepository repo2)
        {
            reservationRepository = repo ?? new ReservationRepository(new PergoDBEntities());
            storeRepository = repo2 ?? new StoreRepository(new PergoDBEntities());
        }

        // GET: Admin/ReservationAdmin
        public ActionResult Index(ReservationIndexView model)
        {
            var query = reservationRepository.Query(model.IsReply).OrderByDescending(r => r.ReservationTime);
            var pageResult = query.ToPageResult<Reservation>(model);
            model.PageResult = Mapper.Map<PageResult<ReservationView>>(pageResult);
            return View(model);
        }

        public ActionResult Edit(int id = 0)
        {
            ReservationView model;
            if (id == 0)
            {
                model = new ReservationView();
                model.ReservationTime = DateTime.Now;
                model.ReservationTimeStr = model.ReservationTime.ToString("yyyy/MM/dd HH:mm");
            }
            else
            {
                var query = reservationRepository.GetById(id);
                model = Mapper.Map<ReservationView>(query);
                model.ReservationTimeStr = model.ReservationTime.ToString("yyyy/MM/dd HH:mm");
                model.StoreName = storeRepository.GetById(Convert.ToInt32(model.Store)).StoreName;
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit(ReservationView model)
        {
            model.ReservationTime = Convert.ToDateTime(model.ReservationTimeStr);
            if (ModelState.IsValid)
            {   
                Reservation reservation = Mapper.Map<Reservation>(model);
                if (model.ID == 0)
                {
                    reservation.CreateDate = DateTime.Now;
                    model.ID = reservationRepository.Insert(reservation);
                }
                else
                {
                    reservationRepository.Update(reservation);
                }
                ShowMessage(true, "");
                return RedirectToAction(nameof(ReservationAdminController.Edit), new { id = model.ID });
            }

            ShowMessage(false, "輸入資料有誤");
            return View(model);
        }

        public ActionResult Delete(int id)
        {
            Reservation reservation = reservationRepository.GetById(id);
            reservationRepository.Delete(reservation.ID);
            ShowMessage(true, "Data deleted.");
            return RedirectToAction(nameof(ReservationAdminController.Index));
        }
    }
}

Pergo/Areas/Admin/Views/ReservationAdmin/Edit.cshtml
@model Pergo.Areas.Admin.ViewModels.Reservation.ReservationView
@{
    ViewBag.Title = "Edit";
}

<section class="content-header">
    <h1>
        預約管理
    </h1>
</section>

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">編輯</h3>
                </div>

                @using (Html.BeginForm("Edit", "ReservationAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {

                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.ID)
                    @Html.HiddenFor(model => model.CreateDate)
                    @Html.HiddenFor(model => model.Store)

                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name)
                            @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @readonly = "true" })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Type)
                            @Html.DropDownListFor(model => model.Type, Model.ReservationTypeOptions, new { @class = "form-control", @readonly = "true" })
                            @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                        </div>

                         <div class="form-group">
                            @Html.LabelFor(model => model.Phone)
                            @Html.TextBoxFor(model => model.Phone, new { @class = "form-control", @readonly = "true" })
                        </div>

                         <div class="form-group">
                            @Html.LabelFor(model => model.Address)
                            @Html.TextBoxFor(model => model.Address, new { @class = "form-control", @readonly = "true" })
                        </div>

                         <div class="form-group">
                            @Html.LabelFor(model => model.Store)
                            @Html.TextBoxFor(model => model.StoreName, new { @class = "form-control", @readonly = "true" })
                        </div>

                         <div class="form-group">
                            @Html.LabelFor(model => model.Email)
                            @Html.TextBoxFor(model => model.Email, new { @class = "form-control", @readonly = "true" })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>

                         <div class="form-group">
                            @Html.LabelFor(model => model.InquiryContent)
                            @Html.TextAreaFor(model => model.InquiryContent, new { @class = "form-control js-ckeditor", @readonly = "true" })
                        </div>

                         <div class="form-group">
                            @Html.LabelFor(model => model.ReservationTime)
                            @Html.TextBoxFor(model => model.ReservationTimeStr, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.ReservationTime, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-check">
                            @Html.CheckBoxFor(model => model.IsReply, new { @class = "form-check-input" })
                            <label class="form-check-label" for="check-box-status">
                                @Html.DisplayNameFor(model => model.IsReply)
                            </label>
                        </div>
                    </div>
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">儲存</button>
                        @Html.ActionLink("取消/回列表", "Index", null, new { @class = "btn btn-default" })
                    </div>
                }
            </div>
        </div>
    </div>
</section>

@section scripts{
    <!--datetimepicker-->
    <link href="~/Content/bootstrap-datetimepicker-master/css/bootstrap-datetimepicker.min.css" rel="stylesheet" />
    <script src="~/Content/bootstrap-datetimepicker-master/js/bootstrap-datetimepicker.js"></script>
    <script>
        $(function () {
            //datetimepicker
            $.prototype.datetimepicker.DPGlobal.nonpunctuation = /[^ -\/:-@@\[-`{-~\t\n\rZ]+/g;
            var currentDate = new Date();
            currentDate.setMinutes(0, 0, 0);
            currentDate.setHours(currentDate.getHours() + currentDate.getTimezoneOffset() / 60);
            $('#ReservationTimeStr').datetimepicker({
                todayHighlight: true,
                weekStart: 1,
                minView: 0,
                autoclose: true,
                //pickerPosition: 'bottom-left',
                format: 'yyyy/mm/dd hh:ii ',
                //timezone: 'UTC',
                startDate: currentDate,
            });
        });
    </script>
}

Pergo/Areas/Admin/Views/ReservationAdmin/Index.cshtml
@model Pergo.Areas.Admin.ViewModels.Reservation.ReservationIndexView
@{
    ViewBag.Title = "Index";
}

<section class="content-header">
    <h1>
        預約管理
    </h1>
</section>

<section class="content">
    <div class="row">
        <!--搜尋條件-->
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">搜尋</h3>
                </div>
                @using (Html.BeginForm("Index", "ReservationAdmin", FormMethod.Get, new { @class = "form-horizontal" }))
                {
                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.SearchValue, new { @class = "col-sm-2 control-label" })
                            <div class="col-sm-10">
                                @Html.TextBoxFor(model => model.SearchValue, new { @class = "form-control", @id = "SeriesName", @placeholder = "系列名稱" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.IsReply, new { @class = "col-sm-2 control-label" })
                            <div class="col-sm-10">
                                @Html.EditorFor(model => model.IsReply, "StatusDropDownList", new { @class = "form-control" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-info">搜尋</button>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>

        <!--清單-->
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">預約列表</h3>
                </div>
                <div class="box-body">
                    <div id="dataList_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                        @Html.Partial("_PageSizeAdmin", Model.PageResult)
                        <div class="row">
                            <div class="col-sm-12">
                                <table class="table table-bordered table-hover dataTable">
                                    <thead>
                                        <tr>
                                            <th>
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().ID)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().Name)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().Email) / @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().Phone)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().IsReply)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().ReservationTime)
                                            </th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().ID)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().Name)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().Email) / @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().Phone)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().IsReply)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().ReservationTime)
                                            </th>
                                            <th></th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        @foreach (var item in Model.PageResult.Data)
                                        {
                                            <tr>
                                                <td>
                                                    @item.ID
                                                </td>
                                                <td>
                                                    @item.Name
                                                </td>
                                                <td>
                                                    @item.Email <br />
                                                    @item.Phone
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(model => item.IsReply, "_ReplyStatus")
                                                </td>
                                                <td>
                                                    @item.ReservationTime
                                                </td>
                                                <td>
                                                    @Html.ActionLink("編輯", "Edit", "ReservationAdmin", new { id = item.ID }, new { @class = "btn btn-primary" })
                                                    @*@Html.ActionLink("刪除", "Delete", "ReservationAdmin", new { id = item.ID }, new { @class = "btn btn-danger js-delete-confirm" })*@
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        @Html.Partial("_PageAdmin", Model.PageResult)
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section scripts{
    <script src="~/Scripts/Admin/page.js"></script>
}